
on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Test app
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ci
      POSTGRES_PASSWORD: ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install --upgrade -r requirements.txt
      - run: docker compose build
      - run: docker compose up -d --
      - run: sleep 5
      - run: pytest reqres_tests
        env:
          APP_URL: http://128.0.0.1:8002

      - run: docker compose logs app
        if: always()

  release:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - run: gh release create $(git rev-parse --short HEAD) --generate-notes

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - run: echo "Deploying"
